name: bm_security
description: "BM Security - Security Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Storage
  get: ^4.6.5
  get_storage: ^2.1.1
  
  # UI & Styling
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1
  
  # Network & Data
  http: ^1.3.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  
  # Location & Maps
  geolocator: ^13.0.3
  geocoding: ^2.1.1
  google_maps_flutter: ^2.12.2
  
  # Permissions & Background Tasks
  permission_handler: ^11.3.0
  workmanager: ^0.5.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Media & Files
  image_picker: ^1.0.7
  file_picker: ^9.2.1
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.5
  flutter_local_notifications: ^19.2.1
  
  # Splash Screen
  flutter_native_splash: 2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/bm.png"
  remove_alpha_ios: true 
  # Optional for Android adaptive icons:
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "lib/assets/images/icon_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/bm.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/